### ISSUE TITLE
Error can not install

### ISSUE THREAD

**Issue by zeroXBami** [ethereumjs/ethereumjs-abi#67] opened 2018-08-31 16:17 UTC
Hi, 

I am trying to install ethereumjs-abi but always got this issues:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/ethereumjs/ethereumjs-abi.git /Users/trnhgquan/.npm/_cacache/tmp/git-clone-e6ae2501
npm ERR! /Users/trnhgquan/.npm/_cacache/tmp/git-clone-e6ae2501/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trnhgquan/.npm/_logs/2018-08-31T16_15_05_558Z-debug.log

Does anyone here can help me to fix?

Thanks.

**Comment by holgerd77** [comment] 2018-09-21 11:57
You doesn't seem to have the proper rights to write in your given directory. This is nevertheless no abi library related issue, will close.

**Comment by bloodybit** [comment] 2020-08-27 13:19
I faced the same problem and apparently there is a file that needs to be downloaded from git in "git ssh mode" not via https. Adding my github identity with ssh-add solved my issue. I don't think the pubkey is actually checked, it just needs to be non null.

**Comment by Resoguy** [comment] 2021-03-26 17:39
I am getting this Permission denied error on cypress github action while installing dependencies with the `npm ci` command

This is where the error occurs
`/usr/bin/git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git`

This error makes the project untestable on github action. Any idea to how solve?

Here is the full log:

```
/usr/local/bin/npm ci
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-03-26T17_17_00_879Z-debug.log
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

**Comment by Andrea-Dispe** [comment] 2021-07-14 08:22
> I am getting this Permission denied error on cypress github action while installing dependencies with the `npm ci` command
> 
> This is where the error occurs
> `/usr/bin/git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git`
> 
> This error makes the project untestable on github action. Any idea to how solve?
> 
> Here is the full log:
> 
> ```
> /usr/local/bin/npm ci
> npm ERR! Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git
> npm ERR! 
> npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
> npm ERR! git@github.com: Permission denied (publickey).
> npm ERR! fatal: Could not read from remote repository.
> npm ERR! 
> npm ERR! Please make sure you have the correct access rights
> npm ERR! and the repository exists.
> npm ERR! 
> npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/runner/.npm/_logs/2021-03-26T17_17_00_879Z-debug.log
> Error: The process '/usr/local/bin/npm' failed with exit code 1
> ```

I am getting the same error on Mac and Ubuntu. Have you solved this issue @Resoguy

**Comment by bloodybit** [comment] 2021-07-14 09:12
I think you can solve it this way: https://github.com/ethereumjs/ethereumjs-abi/issues/67#issuecomment-681944008

**Comment by Andrea-Dispe** [comment] 2021-07-15 01:11
> I think you can solve it this way: [#67 (comment)](https://github.com/ethereumjs/ethereumjs-abi/issues/67#issuecomment-681944008)

Thank you but I was able to solve this by updating npm to the latest version.

**Comment by RadioJulius** [comment] 2021-07-21 06:23
I've noticed this occasionally happen when adding a new package with yarn. It will revert from the working:
 
` "resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"`

to the non-working:

`"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"`

Manually switching back fixes this headache for me.

**Comment by knzeng-e** [comment] 2021-09-27 15:49
> I've noticed this occasionally happen when adding a new package with yarn. It will revert from the working:
> 
> ` "resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"`
> 
> to the non-working:
> 
> `"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"`
> 
> Manually switching back fixes this headache for me.

+1 this comment resolved my issue. Thanks !

**Comment by preconfxsd** [comment] 2021-10-14 14:08
> I faced the same problem and apparently there is a file that needs to be downloaded from git in "git ssh mode" not via https. Adding my github identity with ssh-add solved my issue. I don't think the pubkey is actually checked, it just needs to be non null.

Can you tell me how did you add your identity? Should I add it into workflow yaml file?

**Comment by creazy231** [comment] 2021-10-25 10:39
Same problem using Vercel Deployment

**Comment by vseehausen** [comment] 2021-11-28 17:12
I face this issue now.

**Comment by holgerd77** [comment] 2021-11-29 09:34
@Valentin-Seehausen hi there, I did a test clone + `npm i` on https://github.com/effectai/force-frontend-new - assuming that that's the repository from where your issue originated - but I couldn't even find the dependency, `npm ls ethereumjs-abi` is giving me nothing.

Can you give a short context description where the `ethereumjs-abi` dependency is actually coming from in your context?

**Comment by holgerd77** [comment] 2021-11-29 09:38
And for everyone reading along here: while we have deprecated this package if there is something with reasonable effort we can do here from our side we can very well do a bugfix release here.

It's generally helpful if you provide more context on where are you getting your errors. What Node version are you using? Are you using the `ethereumjs-abi` dependency directly or is it installed via another dependency? Optimally provide some reproduceable code example (or eventually some CLI command lineup in this context).

Thanks!

Will reopen this issue for now until this is settled in some way.

**Comment by djmbritt** [comment] 2021-11-29 13:42
We also encountered this issue last week, it was a deprecated dependency from WalletConnect. 
This was still the 1.0 version of WalletConnect.
We dropped support for WalletConnect for now.

**Comment by holgerd77** [comment] 2021-11-29 14:03
Just to confirm: are there more people here where this problem is coming from the [WalletConnect](https://github.com/walletconnect/walletconnect-monorepo) library?

**Comment by vseehausen** [comment] 2021-11-29 21:28
Yes, it originated from the WalletConnect library. I solved the issue by deleting my yarn.lock and reinstall.
Sorry that I cannot help to reproduce it. Super service, thanks a lot!

**Comment by Kamikozz** [comment] 2022-01-19 13:05
@holgerd77
- it is happened for me on Node v14.17.3
- Installed via another dependency
- Using `npm`

![image](https://user-images.githubusercontent.com/33129671/150134744-4b34a3ea-4d52-4428-83f1-b1bfd3e5883d.png)

```
└─┬ @amfi/connect-wallet@1.1.21
  └─┬ @walletconnect/web3-provider@1.7.1
    └─┬ web3-provider-engine@16.0.1
      └─┬ eth-sig-util@1.4.2
        └── ethereumjs-abi@0.6.8 (git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0)
```

I have just created new app on `heroku`, then made a setup via `github repository` to deploy, and then it showed me these logs
<details>
  <summary>Spoiler warning</summary>
  
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: mars/create-react-app
-----> React.js (create-react-app) multi app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
=====> Detected Framework: Multipack
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 14.x...
       Downloading and installing node 14.18.3...
       Using default npm version: 6.14.15
       
-----> Restoring cache
       - node_modules
       
-----> Installing dependencies
       Installing node modules
       npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git
       npm ERR! 
       npm ERR! Host key verification failed.
       npm ERR! fatal: Could not read from remote repository.
       npm ERR! 
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.
       npm ERR! 
       npm ERR! exited with error code: 128
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.3QAnL/_logs/2022-01-19T07_02_45_160Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile React.js (create-react-app) multi app.
 !     Push failed
 ```
  
</details>
 
 No matter what it says, there is no problem with `buildpack`, it's just something that is here `git ls-remote -h -t ssh://git@github.com/ethereumjs/ethereumjs-abi.git`
 
 Anyway, you can try this command locally and it will show you this error.

But, if I run my project locally, everything is working (this could be the GitHub policy about SSH, dunno)

#### // SOLVED: using `yarn` instead of `npm` will give you the pleasure

**Comment by nbeuchat** [comment] 2022-03-17 22:24
In my case, the problem comes from the [`@web3-onboard/walletlink`](https://www.npmjs.com/package/@web3-onboard/walletlink) package.

**Comment by ayudh37** [comment] 2022-03-24 03:12
I had this issue as well, using when using @walletconnect/web3-provider and using npm as the package manager. 

I deleted package-lock.json and node_modules and used yarn to install the modules. Verified that the resolve url for the dependency ethereumjs-abi begins with `https://` instead of `git+ssh://` in yarn.lock and everything works now

**Comment by mdarche** [comment] 2022-04-19 17:24
For anybody struggling with this issue using pnpm, I fixed by adding an override to my root package.json:
```  
"pnpm": {
    "overrides": {
      "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
    }
  }
  ```

Reference: https://pnpm.io/package_json#pnpmoverrides

**Comment by georgeperry1** [comment] 2022-05-09 08:18
I was having this issue specifically when installing and deploying within an AWS Amplify build pipeline. Of the suggested fixes, moving from `npm` to `yarn` was the only thing that solved it for me.

**Comment by akorede12** [comment] 2022-05-17 16:29
> Same problem using Vercel Deployment

Yes I'm having this issue now trying to deploy my project on vercel. how do you solve the issue when deploying to vercel?

**Comment by Hazelwu2** [comment] 2022-06-13 16:41
> > Same problem using Vercel Deployment
> 
> Yes I'm having this issue now trying to deploy my project on vercel. how do you solve the issue when deploying to vercel?

I'm using vercel cicd to deploy my project, has the same problem.
remove `package.lock` & `yarn.lock`, and `yarn install` reinstall again, that's work for me!

**Comment by rstellar** [comment] 2022-06-27 21:16
Having this issue using `npm ci` via [Cyclic.sh](https://www.cyclic.sh/)

**Comment by zubin-madon** [comment] 2022-07-02 10:19
> "resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"

I am facing this issue while trying to build my app on Netlify. https://app.netlify.com/sites/effortless-cocada-30ceed/deploys/62c019e951f0c30008112b2d

In my packagelock.json I see the following:
```
"node_modules/ethereumjs-abi": {
      "version": "0.6.8",
      "resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0",
      "license": "MIT",
      "dependencies": {
        "bn.js": "^4.11.8",
        "ethereumjs-util": "^6.0.0"
      }
      ```

**Comment by WanderKey** [comment] 2022-07-11 01:34
I faced this issue while using yarn to get the dependences, I disabled SSL Verification by running:
_git config --global http.sslVerify "false"_
and it worked!
![Erro (2)](https://user-images.githubusercontent.com/50473226/178172548-002c95f9-795c-44fa-8281-a05c6ab51e2b.png)

**Comment by illepic** [comment] 2022-08-01 16:13
For yarn users, add this to the root of `package.json`:

```json
  "resolutions": {
    "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
  }
```

**Comment by selmi-karim** [comment] 2022-08-19 11:22
same issue on Digital ocean.

**Comment by lucasuema** [comment] 2022-09-15 16:25
> I've noticed this occasionally happen when adding a new package with yarn. It will revert from the working:
> 
> ` "resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"`
> 
> to the non-working:
> 
> `"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"`
> 
> Manually switching back fixes this headache for me.

I ❤️ u

**Comment by 0xnogo** [comment] 2022-09-17 12:18
Had the issue using vercel.

Removed `yarn.lock`, `package-lock.json` and used yarn. Dependencies fetching is now working.

**Comment by sztadii** [comment] 2022-09-26 11:14
> For anybody struggling with this issue using pnpm, I fixed by adding an override to my root package.json:
> 
> ```
> "pnpm": {
>     "overrides": {
>       "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
>     }
>   }
> ```
> 
> Reference: https://pnpm.io/package_json#pnpmoverrides

if someone is using yarn monorepo I suggest adding it to the main package.json file

**Comment by sztadii** [comment] 2022-09-26 11:16
> For yarn users, add this to the root of `package.json`:
> 
> ```json
>   "resolutions": {
>     "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
>   }
> ```

If someone is using yarn workspaces I suggest adding it to the main package.json file. The children package.json files did not work for me.

**Comment by sbinft-hiwatashi** [comment] 2022-10-05 11:50
same issue from wallet connect modules on my github actions.

**Comment by sbinft-hiwatashi** [comment] 2022-10-05 12:18
I solved this issue for following.
Remove ```"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"``` from my yarn.lock and re-run ```yean install```,
then yarn.lock was updated to git+https url.

It's works for me, but I don't know if this is right way.

**Comment by dcsan** [comment] 2022-10-06 05:50
did anyone figure out how to fix this when you're on a vercel env, where you can't easily add an .ssh key?
my dependency is coming from wagmi.sh 

which i have updated to the latest:

```
$ yarn why ethereumjs-abi
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ethereumjs-abi"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ethereumjs-abi@0.6.8"
info Reasons this module exists
   - "wagmi#@coinbase#wallet-sdk#eth-json-rpc-filters#eth-json-rpc-middleware#eth-sig-util" depends on it
   - Hoisted from "wagmi#@coinbase#wallet-sdk#eth-json-rpc-filters#eth-json-rpc-middleware#eth-sig-util#ethereumjs-abi"
info Disk size without dependencies: "456KB"
info Disk size with unique dependencies: "780KB"
info Disk size with transitive dependencies: "13.48MB"
info Number of shared dependencies: 19
✨  Done in 0.22s.
```

FWIW the `yarn.lock` has these fields:

```
eth-sig-util@^1.4.2:
  version "1.4.2"
  resolved "https://registry.npmjs.org/eth-sig-util/-/eth-sig-util-1.4.2.tgz"
  integrity sha512-iNZ576iTOGcfllftB73cPB5AN+XUQAT/T8xzsILsghXC1o8gJUqe3RHlcDqagu+biFpYQ61KQrZZJza8eRSYqw==
  dependencies:
    ethereumjs-abi "git+https://github.com/ethereumjs/ethereumjs-abi.git"
    ethereumjs-util "^5.1.1"


"ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git":
  version "0.6.8"
  resolved "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"
  dependencies:
    bn.js "^4.11.8"
    ethereumjs-util "^6.0.0"

```

and this buggy fucking package has their git+ssh shit in there.

![image](https://user-images.githubusercontent.com/514002/194224906-24caa8d7-9efc-495c-ad82-7aa00b27b01f.png)

**Comment by dcsan** [comment] 2022-10-06 06:19
ok so the solution of deleting the git+ssh entry and manually hacking the yarn.lock and reinstalling seems to work.
but how fragile is this? 
what are the cases that will cause the yarn.lock to be completely rebuilt?

**Comment by dcsan** [comment] 2022-10-06 06:22
also, what can we recommend upstream packages to do that depend on this? even tho this package is [deprecated](https://github.com/ethereumjs/ethereumjs-abi/issues/67#issuecomment-981455307) as of a year ago, it seems very recent other modules still depend on it.

my deps path:

   - "wagmi#@coinbase#wallet-sdk#eth-json-rpc-filters#eth-json-rpc-middleware#eth-sig-util" depends on it

this issue says in fact that `coinbase/wallet` is the RIGHT thing to use...

https://github.com/blocknative/web3-onboard/issues/885

**Comment by holgerd77** [comment] 2022-10-06 09:57
Hi there,
we are very open to do a quick bugfix release on our side if this helps, even if this package is deprecated, I just haven't identified if we can do something on our side.

If you follow-up the dependency path and find the right place where to post the issue "on the other side" feel free to mention me, then we can coordinate on how to fix this and see if we can also do something from the EthereumJS side of things.

**Comment by dcsan** [comment] 2022-10-06 18:30
thanks @holgerd77 someone tracked the deps tree here for wagmi.
not sure how you could fix it at this end - can you replace the module/version and replace the git with https?

https://github.com/wagmi-dev/wagmi/discussions/1027

**Comment by masterbd** [comment] 2022-10-20 10:55
What I've done to fix this on local and CI:

Replace in **package-lock.json**:
`"ethereumjs-abi": "git+https://github.com/ethereumjs/ethereumjs-abi.git"`
or
`"ethereumjs-abi":"git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git"`
**With:**
`"ethereumjs-abi": "^0.6.8"`

Replace in **package-lock.json**:
`"resolved": "git+https://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"`
or:
```"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"```
**With:** 
`"resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"`

Replace in **package-lock.json**
```
"ethereumjs-abi": {
      "version": "git+https://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0",
      "from": "ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git"
      ....
}
```
**With:** 
```
"ethereumjs-abi": {
      "version": "^0.6.8",
      "resolved": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz",
      ....
}
```

**Comment by arshamg** [comment] 2022-10-27 03:48
Is there a non-fragile/definitive solution to this using npm?

**Comment by eth0izzle** [comment] 2022-11-01 13:45
Yes @arshamg. Delete your `package-lock.json` and `yarn.lock` files then simply add the below to your `package.json`. This will work regardless of npm/yarn.

```
  "resolutions": {
    "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
  },
```

**Comment by arshamg** [comment] 2022-11-01 16:47
Thanks @eth0izzle

**Comment by lazy1523** [comment] 2022-11-06 12:54
Why this damn problem hasn't been solved and it's holding the crypto industry back

**Comment by acolytec3** [comment] 2022-11-07 22:01
Can someone on this thread who's encountered the issue provide an example repo where this issue occurs so I can reproduce locally?  I've looked at the various dependencies in the stack that reference the old version of `ethereumjs-abi` that seems to be causing the issue and I'm not able to reproduce it.  If I can indeed validate the issue (and which setup is causing it to break), I can try and work with whichever dependent module is causing things to break to update their deps.  If I had to guess, I'd say it's most likely the `eth-json-rpc-filters` module since its most current version references older other libraries that in turn lead down to that git referenced version of `ethereumjs-abi`.

**Comment by aahna-ashina** [comment] 2022-11-15 06:28
Solved by running `yarn upgrade`

**Comment by lucasuema** [comment] 2022-11-15 11:52
> Solved by running `yarn upgrade`

Thank you! 👹 - It solved it for me too.

**Comment by LintonAchmad** [comment] 2022-11-25 06:33
Had the same issue, switching to yarn from npm did the trick.

1 - Install yarn : npm install -g yarn
2 - Delete package lock file from root of project.
3 - Run yarn in root of project.

**Comment by algmir** [comment] 2022-12-13 05:45
I try it by aboved answers and can not solve it , it cost about me 1.5days. I use next , it worked, share the website to help others.
npm i @truffle/hdwallet-provider@next
https://stackoverflow.com/questions/71396470/cannot-install-npm-package-code-128-an-unknown-git-error-occurred

**Comment by Soecka** [comment] 2022-12-14 13:15
> For anybody struggling with this issue using pnpm, I fixed by adding an override to my root package.json:
> 
> ```
> "pnpm": {
>     "overrides": {
>       "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
>     }
>   }
> ```
> 
> Reference: https://pnpm.io/package_json#pnpmoverrides

I upgraded pnpm from 6.9 to 7.18 and then the bug was resolved

**Comment by AllanBUSI** [comment] 2023-05-08 14:06
> > > Même problème avec Vercel Deployment
> > 
> > 
> > Oui, j'ai ce problème en essayant de déployer mon projet sur vercel. comment résolvez-vous le problème lors du déploiement sur vercel ?
> 
> J'utilise Vercel Cicd pour déployer mon projet, j'ai le même problème. supprimer `package.lock`& `yarn.lock`, et `yarn install`réinstaller à nouveau, ça marche pour moi !

thanck you

**Comment by 0xabz** [comment] 2023-05-23 14:21
> Yes @arshamg. Delete your `package-lock.json` and `yarn.lock` files then simply add the below to your `package.json`. This will work regardless of npm/yarn.
> 
> ```
>   "resolutions": {
>     "ethereumjs-abi": "https://registry.npmjs.org/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz"
>   },
> ```

nice!!!!!!!! fix this problem!!! thank you!!!

**Comment by arsqu** [comment] 2023-08-03 06:23
> I solved this issue for following. Remove `"resolved": "git+ssh://git@github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"` from my yarn.lock and re-run `yean install`, then yarn.lock was updated to git+https url.
> 
> It's works for me, but I don't know if this is right way.

thanks, it works for me

**Comment by finorix079** [comment] 2023-10-29 19:42
I have this same problem when I was trying to build my project via AWS Ampify. It is serverless so I guess there's no way for me to add my ssh key there. (The repo I used is a private repo of mine, though.) Does anyone have the solution for a serverless service like that?

**Comment by blazejkrzak** [comment] 2023-11-28 12:11
I had this problem when I logged to the server via SSH.
I forgot to forward my agent via `-A` flag.

`ssh -A $user:$host` 
I leave it here, probably for myself in the future and maybe for the others that encounter this issue

**Closed** 2024-10-30 10:47 UTC
